name: HNG CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install black

      - name: Check code formatting with Black
        run: |
          black --check Backend

      - name: Run Python syntax check
        run: |
          python -m py_compile $(find Backend -name "*.py")

      - name: Verify FastAPI app can start
        run: |
          uvicorn Backend.main:app --host 127.0.0.1 --port 8000 &
          sleep 3
          curl -f http://127.0.0.1:8000 || (echo "❌ App failed to start" && exit 1)
          pkill -f uvicorn

      - name: Confirm workflow completion
        run: echo "✅ HNG CI completed successfully!"
